#############################
## Caitlin J. Corbin       ##
## Complement a DNA strand ##
#############################

dna_string = 'CGCCATACTACCTACCTTAGACCCTCGCCGACTATTCCCCGCCGCAGGTAATATCCCCTAGCAATCCCGTAACTCCCAGACACCTTGCTCATGTCATGTCTCATGTAGGTAAAAACTGTCGTGTGATTAAACTAAACGCAAGGTAGAAGGATGAGCCCCGGTCGTCTCCCGCGCAACCAATACTAACAGGTCTCTCTTGCACGCACCGCCAAGTCCGGGGCCGTGCATACCGTTAACTGTCAAGAAGGCGACCTAAGACACGTCAATACGCCGCTTACTGGAACGGCGGATCTTAGGTGTACCTGCAGGCAATGATCACAGGACCAATCCTGCATGGAGGGACGTTTCCATATGTATGAACACATGCGCAGTCCGCTTCGGACTGGTCCCGTATGTTTAGAAGGCGGCAAGCGTTAGTCTCAATACTAAGTTTATCCCACCTCGTATCTTGTTCGACACACAGTGGACCAAGTGATACCAAGGCTTATTAGCGCAACTTGGCGAACACCGTATTCGCCTCTGTGAGACGTTAAGGGTTGAACCTATTCCGGCCACAGATGGCAGCGAAGATGGTGCCGAGCAAGCTGCATCGACTATGGCTAAGTGAGGGCTCGCAGGAGATTCGGACGGCTGACTTGATTCTGACTCTTGACGATCGGCCTCAATTAATCTCAAGCCTAACCAGGTATTGGGATTGAGTCTCAGTCATAAAGAGCCAATCCCCTGTATTTGGCCAGCTAGACCTCCGAGGTGCTTCTCTATGAGTCCCATTCTACACCTTAACAACGGGCCCGGTGGGAAGGGACAATCTGCACTGGAGAGTAACAATTGTATATACGGCAGGGTGCGTGATAATGCCGCGTTCATTGGGATGCGCGGTCTGCTGCTACAGCCGTGCATAAGCTCTGTTAAACAATTTACCCACCTTCAGTATGCGAAAACCTGCCACGAGATCCGGACCCCTACCGGGGC'

rev_dna = list(dna_string[::-1])


#print(rev_dna, '\n') test
i = 0
for i in range (len(rev_dna)):
    if rev_dna[i] == 'A':
        rev_dna[i] = 'T'
    elif rev_dna[i] == 'T':
        rev_dna[i] = 'A'
    elif rev_dna[i] == 'G':
        rev_dna[i] = 'C'
    elif rev_dna[i] == 'C':
        rev_dna[i] = 'G'

dna_complement = ''.join([str(x) for x in rev_dna])
print(dna_complement)
