############################################
## Caitlin J. Corbin                      ##
## Transcribes DNA strand to RNA strand   ##
############################################

dna = 'TATCCACCAGTGGACGGAAGCGAATGGGGGGAGTGATGGCTGCCTCCCGCGCACATAGTACTATTACTATATGTTGAATATTAGTTGCGGTTGATTGGGTTCTGACAATATGGGCAGCTCGCGCCCTTAGCCGGCCCGAGAATAAACACCCCCATATATAAAACATCCAGAATAGGGACCTAATTAAGCTATTTTAGCCTCGGGGCATAAAAGTGCCCGCGTGTTGGTGGGGGTCCGTAGGTTTAAGGCTAGTCATGCGGTGGCTATTCAACATCTCTACGGACGCCCGGAACACGGGGGCACAGGTTAATCAATGAACCAAATCACGAGTGCGGTACAAGATAGAGTTCTCGACGCGCTGGTTTCTCCCCAGTAAAAAATTTCAGGTGCATGTCTAGTATGAATGCCCGGGATGGTGAGATGTCCCCAAGAACCCTTAATGCTTAAGGAGATTTACTCTGATTTGGTGTCACGTCTTTGCTCGCATATCCAAAACCCCGTACTACCAGTCAAAGGCGGTCACCTAATATCACGTTTCCGTTAACCGATGAGGATCGCTGATGTGCGGCTAGGTCACGATAATACCTCCATCCAAAGTTAAGCATTCACGCCCCCACATTCTGACTTGAAATTCGCTGACCTCTACCTCCATGTTTACGGTGCCATATTCGTTATCGCCGTTGATCCTTTCGGCATAGGTTGGCCTAGTATGCATGGCCGCACAAATTGTACTTATGACCTGGCTGCCCTCGTAGTGCCGTTACACATTCCGCTAGGCCGATGAATGAGCTCGGTTGTACGGTCTCTATGCTATGGAATATGTACGGTAAAGTGTGTGTACACCCGCTACGTGCTTTGTCGACTTGAACACTCCAACCTTGTCTCCGCGGTTATCGCGACCTGAAGCTTGCCAATTTG'
arr = list(dna)

for x in range (len(arr)):
    if arr[x] == 'T':
        arr[x] = 'U'

str = ''.join([str(x) for x in arr])

print(str)